# Generated by Django 4.2.5 on 2023-10-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycustomuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
