# Generated by Django 4.2.5 on 2023-10-02 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'ordering': ['-sender'], 'verbose_name': 'Отправка сообщения', 'verbose_name_plural': 'Отправка сообщений'},
        ),
    ]
